name: engine
description: 고스톱(Go-Stop) 카드게임 룰 엔진
version: 0.1.0
repository: https://github.com/sfex11/gostop

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
